// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package seleniummodule.proxies;

public class SeleniumOutput
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject seleniumOutputMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SeleniumModule.SeleniumOutput";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ErrorMessage("ErrorMessage"),
		HasError("HasError"),
		OutputURL("OutputURL");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SeleniumOutput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SeleniumOutput(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject seleniumOutputMendixObject)
	{
		if (seleniumOutputMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, seleniumOutputMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.seleniumOutputMendixObject = seleniumOutputMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SeleniumOutput.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static seleniummodule.proxies.SeleniumOutput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return seleniummodule.proxies.SeleniumOutput.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static seleniummodule.proxies.SeleniumOutput initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new seleniummodule.proxies.SeleniumOutput(context, mendixObject);
	}

	public static seleniummodule.proxies.SeleniumOutput load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return seleniummodule.proxies.SeleniumOutput.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage()
	{
		return getErrorMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ErrorMessage.toString());
	}

	/**
	 * Set value of ErrorMessage
	 * @param errormessage
	 */
	public final void setErrorMessage(java.lang.String errormessage)
	{
		setErrorMessage(getContext(), errormessage);
	}

	/**
	 * Set value of ErrorMessage
	 * @param context
	 * @param errormessage
	 */
	public final void setErrorMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String errormessage)
	{
		getMendixObject().setValue(context, MemberNames.ErrorMessage.toString(), errormessage);
	}

	/**
	 * @return value of HasError
	 */
	public final java.lang.Boolean getHasError()
	{
		return getHasError(getContext());
	}

	/**
	 * @param context
	 * @return value of HasError
	 */
	public final java.lang.Boolean getHasError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasError.toString());
	}

	/**
	 * Set value of HasError
	 * @param haserror
	 */
	public final void setHasError(java.lang.Boolean haserror)
	{
		setHasError(getContext(), haserror);
	}

	/**
	 * Set value of HasError
	 * @param context
	 * @param haserror
	 */
	public final void setHasError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean haserror)
	{
		getMendixObject().setValue(context, MemberNames.HasError.toString(), haserror);
	}

	/**
	 * @return value of OutputURL
	 */
	public final java.lang.String getOutputURL()
	{
		return getOutputURL(getContext());
	}

	/**
	 * @param context
	 * @return value of OutputURL
	 */
	public final java.lang.String getOutputURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OutputURL.toString());
	}

	/**
	 * Set value of OutputURL
	 * @param outputurl
	 */
	public final void setOutputURL(java.lang.String outputurl)
	{
		setOutputURL(getContext(), outputurl);
	}

	/**
	 * Set value of OutputURL
	 * @param context
	 * @param outputurl
	 */
	public final void setOutputURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String outputurl)
	{
		getMendixObject().setValue(context, MemberNames.OutputURL.toString(), outputurl);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return seleniumOutputMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final seleniummodule.proxies.SeleniumOutput that = (seleniummodule.proxies.SeleniumOutput) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
