// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public class AFABFields
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aFABFieldsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MercedesPOC.AFABFields";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AFABField("AFABField"),
		IsBasedOnGeography("IsBasedOnGeography"),
		IsFromAFAB("IsFromAFAB"),
		DefaultValue("DefaultValue");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AFABFields(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AFABFields(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aFABFieldsMendixObject)
	{
		if (aFABFieldsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, aFABFieldsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.aFABFieldsMendixObject = aFABFieldsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AFABFields.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mercedespoc.proxies.AFABFields initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mercedespoc.proxies.AFABFields.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mercedespoc.proxies.AFABFields initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mercedespoc.proxies.AFABFields(context, mendixObject);
	}

	public static mercedespoc.proxies.AFABFields load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mercedespoc.proxies.AFABFields.initialize(context, mendixObject);
	}

	public static java.util.List<mercedespoc.proxies.AFABFields> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mercedespoc.proxies.AFABFields.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of AFABField
	 * @param afabfield
	 */
	public final mercedespoc.proxies.ENUM_AFABFields getAFABField()
	{
		return getAFABField(getContext());
	}

	/**
	 * @param context
	 * @return value of AFABField
	 */
	public final mercedespoc.proxies.ENUM_AFABFields getAFABField(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.AFABField.toString());
		if (obj == null) {
			return null;
		}
		return mercedespoc.proxies.ENUM_AFABFields.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of AFABField
	 * @param afabfield
	 */
	public final void setAFABField(mercedespoc.proxies.ENUM_AFABFields afabfield)
	{
		setAFABField(getContext(), afabfield);
	}

	/**
	 * Set value of AFABField
	 * @param context
	 * @param afabfield
	 */
	public final void setAFABField(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.ENUM_AFABFields afabfield)
	{
		if (afabfield != null) {
			getMendixObject().setValue(context, MemberNames.AFABField.toString(), afabfield.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.AFABField.toString(), null);
		}
	}

	/**
	 * @return value of IsBasedOnGeography
	 */
	public final java.lang.Boolean getIsBasedOnGeography()
	{
		return getIsBasedOnGeography(getContext());
	}

	/**
	 * @param context
	 * @return value of IsBasedOnGeography
	 */
	public final java.lang.Boolean getIsBasedOnGeography(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsBasedOnGeography.toString());
	}

	/**
	 * Set value of IsBasedOnGeography
	 * @param isbasedongeography
	 */
	public final void setIsBasedOnGeography(java.lang.Boolean isbasedongeography)
	{
		setIsBasedOnGeography(getContext(), isbasedongeography);
	}

	/**
	 * Set value of IsBasedOnGeography
	 * @param context
	 * @param isbasedongeography
	 */
	public final void setIsBasedOnGeography(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isbasedongeography)
	{
		getMendixObject().setValue(context, MemberNames.IsBasedOnGeography.toString(), isbasedongeography);
	}

	/**
	 * @return value of IsFromAFAB
	 */
	public final java.lang.Boolean getIsFromAFAB()
	{
		return getIsFromAFAB(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFromAFAB
	 */
	public final java.lang.Boolean getIsFromAFAB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsFromAFAB.toString());
	}

	/**
	 * Set value of IsFromAFAB
	 * @param isfromafab
	 */
	public final void setIsFromAFAB(java.lang.Boolean isfromafab)
	{
		setIsFromAFAB(getContext(), isfromafab);
	}

	/**
	 * Set value of IsFromAFAB
	 * @param context
	 * @param isfromafab
	 */
	public final void setIsFromAFAB(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isfromafab)
	{
		getMendixObject().setValue(context, MemberNames.IsFromAFAB.toString(), isfromafab);
	}

	/**
	 * @return value of DefaultValue
	 */
	public final java.lang.String getDefaultValue()
	{
		return getDefaultValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultValue
	 */
	public final java.lang.String getDefaultValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DefaultValue.toString());
	}

	/**
	 * Set value of DefaultValue
	 * @param defaultvalue
	 */
	public final void setDefaultValue(java.lang.String defaultvalue)
	{
		setDefaultValue(getContext(), defaultvalue);
	}

	/**
	 * Set value of DefaultValue
	 * @param context
	 * @param defaultvalue
	 */
	public final void setDefaultValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String defaultvalue)
	{
		getMendixObject().setValue(context, MemberNames.DefaultValue.toString(), defaultvalue);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aFABFieldsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mercedespoc.proxies.AFABFields that = (mercedespoc.proxies.AFABFields) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
