// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public class COO
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cOOMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MercedesPOC.COO";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OrderNumber("OrderNumber"),
		Status("Status"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		HadErrorImportingAFAB("HadErrorImportingAFAB"),
		HadErrorSubmittingIHKDraft("HadErrorSubmittingIHKDraft"),
		HadManualChanges("HadManualChanges"),
		IHkDraftURL("IHkDraftURL"),
		COO_COO_IHKdetail("MercedesPOC.COO_COO_IHKdetail"),
		COO_Geography("MercedesPOC.COO_Geography");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public COO(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected COO(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cOOMendixObject)
	{
		if (cOOMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, cOOMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cOOMendixObject = cOOMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'COO.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mercedespoc.proxies.COO initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mercedespoc.proxies.COO.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mercedespoc.proxies.COO initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mercedespoc.proxies.COO(context, mendixObject);
	}

	public static mercedespoc.proxies.COO load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mercedespoc.proxies.COO.initialize(context, mendixObject);
	}

	public static java.util.List<mercedespoc.proxies.COO> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mercedespoc.proxies.COO.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OrderNumber
	 */
	public final java.lang.String getOrderNumber()
	{
		return getOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderNumber
	 */
	public final java.lang.String getOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OrderNumber.toString());
	}

	/**
	 * Set value of OrderNumber
	 * @param ordernumber
	 */
	public final void setOrderNumber(java.lang.String ordernumber)
	{
		setOrderNumber(getContext(), ordernumber);
	}

	/**
	 * Set value of OrderNumber
	 * @param context
	 * @param ordernumber
	 */
	public final void setOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ordernumber)
	{
		getMendixObject().setValue(context, MemberNames.OrderNumber.toString(), ordernumber);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final mercedespoc.proxies.ENUM_ProcessStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final mercedespoc.proxies.ENUM_ProcessStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return mercedespoc.proxies.ENUM_ProcessStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(mercedespoc.proxies.ENUM_ProcessStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.ENUM_ProcessStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * @return value of HadErrorImportingAFAB
	 */
	public final java.lang.Boolean getHadErrorImportingAFAB()
	{
		return getHadErrorImportingAFAB(getContext());
	}

	/**
	 * @param context
	 * @return value of HadErrorImportingAFAB
	 */
	public final java.lang.Boolean getHadErrorImportingAFAB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HadErrorImportingAFAB.toString());
	}

	/**
	 * Set value of HadErrorImportingAFAB
	 * @param haderrorimportingafab
	 */
	public final void setHadErrorImportingAFAB(java.lang.Boolean haderrorimportingafab)
	{
		setHadErrorImportingAFAB(getContext(), haderrorimportingafab);
	}

	/**
	 * Set value of HadErrorImportingAFAB
	 * @param context
	 * @param haderrorimportingafab
	 */
	public final void setHadErrorImportingAFAB(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean haderrorimportingafab)
	{
		getMendixObject().setValue(context, MemberNames.HadErrorImportingAFAB.toString(), haderrorimportingafab);
	}

	/**
	 * @return value of HadErrorSubmittingIHKDraft
	 */
	public final java.lang.Boolean getHadErrorSubmittingIHKDraft()
	{
		return getHadErrorSubmittingIHKDraft(getContext());
	}

	/**
	 * @param context
	 * @return value of HadErrorSubmittingIHKDraft
	 */
	public final java.lang.Boolean getHadErrorSubmittingIHKDraft(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HadErrorSubmittingIHKDraft.toString());
	}

	/**
	 * Set value of HadErrorSubmittingIHKDraft
	 * @param haderrorsubmittingihkdraft
	 */
	public final void setHadErrorSubmittingIHKDraft(java.lang.Boolean haderrorsubmittingihkdraft)
	{
		setHadErrorSubmittingIHKDraft(getContext(), haderrorsubmittingihkdraft);
	}

	/**
	 * Set value of HadErrorSubmittingIHKDraft
	 * @param context
	 * @param haderrorsubmittingihkdraft
	 */
	public final void setHadErrorSubmittingIHKDraft(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean haderrorsubmittingihkdraft)
	{
		getMendixObject().setValue(context, MemberNames.HadErrorSubmittingIHKDraft.toString(), haderrorsubmittingihkdraft);
	}

	/**
	 * @return value of HadManualChanges
	 */
	public final java.lang.Boolean getHadManualChanges()
	{
		return getHadManualChanges(getContext());
	}

	/**
	 * @param context
	 * @return value of HadManualChanges
	 */
	public final java.lang.Boolean getHadManualChanges(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HadManualChanges.toString());
	}

	/**
	 * Set value of HadManualChanges
	 * @param hadmanualchanges
	 */
	public final void setHadManualChanges(java.lang.Boolean hadmanualchanges)
	{
		setHadManualChanges(getContext(), hadmanualchanges);
	}

	/**
	 * Set value of HadManualChanges
	 * @param context
	 * @param hadmanualchanges
	 */
	public final void setHadManualChanges(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hadmanualchanges)
	{
		getMendixObject().setValue(context, MemberNames.HadManualChanges.toString(), hadmanualchanges);
	}

	/**
	 * @return value of IHkDraftURL
	 */
	public final java.lang.String getIHkDraftURL()
	{
		return getIHkDraftURL(getContext());
	}

	/**
	 * @param context
	 * @return value of IHkDraftURL
	 */
	public final java.lang.String getIHkDraftURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IHkDraftURL.toString());
	}

	/**
	 * Set value of IHkDraftURL
	 * @param ihkdrafturl
	 */
	public final void setIHkDraftURL(java.lang.String ihkdrafturl)
	{
		setIHkDraftURL(getContext(), ihkdrafturl);
	}

	/**
	 * Set value of IHkDraftURL
	 * @param context
	 * @param ihkdrafturl
	 */
	public final void setIHkDraftURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ihkdrafturl)
	{
		getMendixObject().setValue(context, MemberNames.IHkDraftURL.toString(), ihkdrafturl);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of COO_COO_IHKdetail
	 */
	public final mercedespoc.proxies.COO_IHKdetail getCOO_COO_IHKdetail() throws com.mendix.core.CoreException
	{
		return getCOO_COO_IHKdetail(getContext());
	}

	/**
	 * @param context
	 * @return value of COO_COO_IHKdetail
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.COO_IHKdetail getCOO_COO_IHKdetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.COO_IHKdetail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.COO_COO_IHKdetail.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.COO_IHKdetail.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of COO_COO_IHKdetail
	 * @param coo_coo_ihkdetail
	 */
	public final void setCOO_COO_IHKdetail(mercedespoc.proxies.COO_IHKdetail coo_coo_ihkdetail)
	{
		setCOO_COO_IHKdetail(getContext(), coo_coo_ihkdetail);
	}

	/**
	 * Set value of COO_COO_IHKdetail
	 * @param context
	 * @param coo_coo_ihkdetail
	 */
	public final void setCOO_COO_IHKdetail(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.COO_IHKdetail coo_coo_ihkdetail)
	{
		if (coo_coo_ihkdetail == null) {
			getMendixObject().setValue(context, MemberNames.COO_COO_IHKdetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.COO_COO_IHKdetail.toString(), coo_coo_ihkdetail.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of COO_Geography
	 */
	public final mercedespoc.proxies.Geography getCOO_Geography() throws com.mendix.core.CoreException
	{
		return getCOO_Geography(getContext());
	}

	/**
	 * @param context
	 * @return value of COO_Geography
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.Geography getCOO_Geography(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.Geography result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.COO_Geography.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.Geography.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of COO_Geography
	 * @param coo_geography
	 */
	public final void setCOO_Geography(mercedespoc.proxies.Geography coo_geography)
	{
		setCOO_Geography(getContext(), coo_geography);
	}

	/**
	 * Set value of COO_Geography
	 * @param context
	 * @param coo_geography
	 */
	public final void setCOO_Geography(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.Geography coo_geography)
	{
		if (coo_geography == null) {
			getMendixObject().setValue(context, MemberNames.COO_Geography.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.COO_Geography.toString(), coo_geography.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cOOMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mercedespoc.proxies.COO that = (mercedespoc.proxies.COO) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
