// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public class COO_IHKdetail
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cOO_IHKdetailMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MercedesPOC.COO_IHKdetail";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Consignor("Consignor"),
		Consignee("Consignee"),
		ReceivingCountry("ReceivingCountry"),
		Status("Status"),
		OriginCountry("OriginCountry"),
		Quantity("Quantity"),
		Remarks("Remarks"),
		MeansOfTransport("MeansOfTransport"),
		AFABGeographyFields("AFABGeographyFields"),
		COO_COO_IHKdetail("MercedesPOC.COO_COO_IHKdetail");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public COO_IHKdetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected COO_IHKdetail(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cOO_IHKdetailMendixObject)
	{
		if (cOO_IHKdetailMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, cOO_IHKdetailMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cOO_IHKdetailMendixObject = cOO_IHKdetailMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'COO_IHKdetail.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mercedespoc.proxies.COO_IHKdetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mercedespoc.proxies.COO_IHKdetail.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mercedespoc.proxies.COO_IHKdetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mercedespoc.proxies.COO_IHKdetail(context, mendixObject);
	}

	public static mercedespoc.proxies.COO_IHKdetail load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mercedespoc.proxies.COO_IHKdetail.initialize(context, mendixObject);
	}

	public static java.util.List<mercedespoc.proxies.COO_IHKdetail> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mercedespoc.proxies.COO_IHKdetail.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Consignor
	 */
	public final java.lang.String getConsignor()
	{
		return getConsignor(getContext());
	}

	/**
	 * @param context
	 * @return value of Consignor
	 */
	public final java.lang.String getConsignor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Consignor.toString());
	}

	/**
	 * Set value of Consignor
	 * @param consignor
	 */
	public final void setConsignor(java.lang.String consignor)
	{
		setConsignor(getContext(), consignor);
	}

	/**
	 * Set value of Consignor
	 * @param context
	 * @param consignor
	 */
	public final void setConsignor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String consignor)
	{
		getMendixObject().setValue(context, MemberNames.Consignor.toString(), consignor);
	}

	/**
	 * @return value of Consignee
	 */
	public final java.lang.String getConsignee()
	{
		return getConsignee(getContext());
	}

	/**
	 * @param context
	 * @return value of Consignee
	 */
	public final java.lang.String getConsignee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Consignee.toString());
	}

	/**
	 * Set value of Consignee
	 * @param consignee
	 */
	public final void setConsignee(java.lang.String consignee)
	{
		setConsignee(getContext(), consignee);
	}

	/**
	 * Set value of Consignee
	 * @param context
	 * @param consignee
	 */
	public final void setConsignee(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String consignee)
	{
		getMendixObject().setValue(context, MemberNames.Consignee.toString(), consignee);
	}

	/**
	 * @return value of ReceivingCountry
	 */
	public final java.lang.String getReceivingCountry()
	{
		return getReceivingCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of ReceivingCountry
	 */
	public final java.lang.String getReceivingCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReceivingCountry.toString());
	}

	/**
	 * Set value of ReceivingCountry
	 * @param receivingcountry
	 */
	public final void setReceivingCountry(java.lang.String receivingcountry)
	{
		setReceivingCountry(getContext(), receivingcountry);
	}

	/**
	 * Set value of ReceivingCountry
	 * @param context
	 * @param receivingcountry
	 */
	public final void setReceivingCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String receivingcountry)
	{
		getMendixObject().setValue(context, MemberNames.ReceivingCountry.toString(), receivingcountry);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final mercedespoc.proxies.ENUM_ProcessStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final mercedespoc.proxies.ENUM_ProcessStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return mercedespoc.proxies.ENUM_ProcessStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(mercedespoc.proxies.ENUM_ProcessStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.ENUM_ProcessStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of OriginCountry
	 */
	public final java.lang.String getOriginCountry()
	{
		return getOriginCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of OriginCountry
	 */
	public final java.lang.String getOriginCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OriginCountry.toString());
	}

	/**
	 * Set value of OriginCountry
	 * @param origincountry
	 */
	public final void setOriginCountry(java.lang.String origincountry)
	{
		setOriginCountry(getContext(), origincountry);
	}

	/**
	 * Set value of OriginCountry
	 * @param context
	 * @param origincountry
	 */
	public final void setOriginCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String origincountry)
	{
		getMendixObject().setValue(context, MemberNames.OriginCountry.toString(), origincountry);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.String getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.String getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.String quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of Remarks
	 */
	public final java.lang.String getRemarks()
	{
		return getRemarks(getContext());
	}

	/**
	 * @param context
	 * @return value of Remarks
	 */
	public final java.lang.String getRemarks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Remarks.toString());
	}

	/**
	 * Set value of Remarks
	 * @param remarks
	 */
	public final void setRemarks(java.lang.String remarks)
	{
		setRemarks(getContext(), remarks);
	}

	/**
	 * Set value of Remarks
	 * @param context
	 * @param remarks
	 */
	public final void setRemarks(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String remarks)
	{
		getMendixObject().setValue(context, MemberNames.Remarks.toString(), remarks);
	}

	/**
	 * @return value of MeansOfTransport
	 */
	public final java.lang.String getMeansOfTransport()
	{
		return getMeansOfTransport(getContext());
	}

	/**
	 * @param context
	 * @return value of MeansOfTransport
	 */
	public final java.lang.String getMeansOfTransport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MeansOfTransport.toString());
	}

	/**
	 * Set value of MeansOfTransport
	 * @param meansoftransport
	 */
	public final void setMeansOfTransport(java.lang.String meansoftransport)
	{
		setMeansOfTransport(getContext(), meansoftransport);
	}

	/**
	 * Set value of MeansOfTransport
	 * @param context
	 * @param meansoftransport
	 */
	public final void setMeansOfTransport(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String meansoftransport)
	{
		getMendixObject().setValue(context, MemberNames.MeansOfTransport.toString(), meansoftransport);
	}

	/**
	 * @return value of AFABGeographyFields
	 */
	public final java.lang.String getAFABGeographyFields()
	{
		return getAFABGeographyFields(getContext());
	}

	/**
	 * @param context
	 * @return value of AFABGeographyFields
	 */
	public final java.lang.String getAFABGeographyFields(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AFABGeographyFields.toString());
	}

	/**
	 * Set value of AFABGeographyFields
	 * @param afabgeographyfields
	 */
	public final void setAFABGeographyFields(java.lang.String afabgeographyfields)
	{
		setAFABGeographyFields(getContext(), afabgeographyfields);
	}

	/**
	 * Set value of AFABGeographyFields
	 * @param context
	 * @param afabgeographyfields
	 */
	public final void setAFABGeographyFields(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String afabgeographyfields)
	{
		getMendixObject().setValue(context, MemberNames.AFABGeographyFields.toString(), afabgeographyfields);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of COO_COO_IHKdetail
	 */
	public final mercedespoc.proxies.COO getCOO_COO_IHKdetail() throws com.mendix.core.CoreException
	{
		return getCOO_COO_IHKdetail(getContext());
	}

	/**
	 * @param context
	 * @return value of COO_COO_IHKdetail
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.COO getCOO_COO_IHKdetail(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.COO result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.COO_COO_IHKdetail.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.COO.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of COO_COO_IHKdetail
	 * @param coo_coo_ihkdetail
	 */
	public final void setCOO_COO_IHKdetail(mercedespoc.proxies.COO coo_coo_ihkdetail)
	{
		setCOO_COO_IHKdetail(getContext(), coo_coo_ihkdetail);
	}

	/**
	 * Set value of COO_COO_IHKdetail
	 * @param context
	 * @param coo_coo_ihkdetail
	 */
	public final void setCOO_COO_IHKdetail(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.COO coo_coo_ihkdetail)
	{
		if (coo_coo_ihkdetail == null) {
			getMendixObject().setValue(context, MemberNames.COO_COO_IHKdetail.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.COO_COO_IHKdetail.toString(), coo_coo_ihkdetail.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cOO_IHKdetailMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mercedespoc.proxies.COO_IHKdetail that = (mercedespoc.proxies.COO_IHKdetail) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
