// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public class COO_AFABDetail
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cOO_AFABDetailMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MercedesPOC.COO_AFABDetail";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FieldName("FieldName"),
		Value("Value"),
		isValid("isValid"),
		errorMessage("errorMessage"),
		COO_AFABDetail_AFABFields("MercedesPOC.COO_AFABDetail_AFABFields"),
		COO_AFABDetail_COO("MercedesPOC.COO_AFABDetail_COO");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public COO_AFABDetail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected COO_AFABDetail(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cOO_AFABDetailMendixObject)
	{
		if (cOO_AFABDetailMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, cOO_AFABDetailMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cOO_AFABDetailMendixObject = cOO_AFABDetailMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'COO_AFABDetail.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mercedespoc.proxies.COO_AFABDetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mercedespoc.proxies.COO_AFABDetail.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mercedespoc.proxies.COO_AFABDetail initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mercedespoc.proxies.COO_AFABDetail(context, mendixObject);
	}

	public static mercedespoc.proxies.COO_AFABDetail load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mercedespoc.proxies.COO_AFABDetail.initialize(context, mendixObject);
	}

	public static java.util.List<mercedespoc.proxies.COO_AFABDetail> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mercedespoc.proxies.COO_AFABDetail.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FieldName
	 */
	public final java.lang.String getFieldName()
	{
		return getFieldName(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldName
	 */
	public final java.lang.String getFieldName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FieldName.toString());
	}

	/**
	 * Set value of FieldName
	 * @param fieldname
	 */
	public final void setFieldName(java.lang.String fieldname)
	{
		setFieldName(getContext(), fieldname);
	}

	/**
	 * Set value of FieldName
	 * @param context
	 * @param fieldname
	 */
	public final void setFieldName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fieldname)
	{
		getMendixObject().setValue(context, MemberNames.FieldName.toString(), fieldname);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @return value of isValid
	 */
	public final java.lang.Boolean getisValid()
	{
		return getisValid(getContext());
	}

	/**
	 * @param context
	 * @return value of isValid
	 */
	public final java.lang.Boolean getisValid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isValid.toString());
	}

	/**
	 * Set value of isValid
	 * @param isvalid
	 */
	public final void setisValid(java.lang.Boolean isvalid)
	{
		setisValid(getContext(), isvalid);
	}

	/**
	 * Set value of isValid
	 * @param context
	 * @param isvalid
	 */
	public final void setisValid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isvalid)
	{
		getMendixObject().setValue(context, MemberNames.isValid.toString(), isvalid);
	}

	/**
	 * @return value of errorMessage
	 */
	public final java.lang.String geterrorMessage()
	{
		return geterrorMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of errorMessage
	 */
	public final java.lang.String geterrorMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.errorMessage.toString());
	}

	/**
	 * Set value of errorMessage
	 * @param errormessage
	 */
	public final void seterrorMessage(java.lang.String errormessage)
	{
		seterrorMessage(getContext(), errormessage);
	}

	/**
	 * Set value of errorMessage
	 * @param context
	 * @param errormessage
	 */
	public final void seterrorMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String errormessage)
	{
		getMendixObject().setValue(context, MemberNames.errorMessage.toString(), errormessage);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of COO_AFABDetail_AFABFields
	 */
	public final mercedespoc.proxies.AFABFields getCOO_AFABDetail_AFABFields() throws com.mendix.core.CoreException
	{
		return getCOO_AFABDetail_AFABFields(getContext());
	}

	/**
	 * @param context
	 * @return value of COO_AFABDetail_AFABFields
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.AFABFields getCOO_AFABDetail_AFABFields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.AFABFields result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.COO_AFABDetail_AFABFields.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.AFABFields.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of COO_AFABDetail_AFABFields
	 * @param coo_afabdetail_afabfields
	 */
	public final void setCOO_AFABDetail_AFABFields(mercedespoc.proxies.AFABFields coo_afabdetail_afabfields)
	{
		setCOO_AFABDetail_AFABFields(getContext(), coo_afabdetail_afabfields);
	}

	/**
	 * Set value of COO_AFABDetail_AFABFields
	 * @param context
	 * @param coo_afabdetail_afabfields
	 */
	public final void setCOO_AFABDetail_AFABFields(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.AFABFields coo_afabdetail_afabfields)
	{
		if (coo_afabdetail_afabfields == null) {
			getMendixObject().setValue(context, MemberNames.COO_AFABDetail_AFABFields.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.COO_AFABDetail_AFABFields.toString(), coo_afabdetail_afabfields.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of COO_AFABDetail_COO
	 */
	public final mercedespoc.proxies.COO getCOO_AFABDetail_COO() throws com.mendix.core.CoreException
	{
		return getCOO_AFABDetail_COO(getContext());
	}

	/**
	 * @param context
	 * @return value of COO_AFABDetail_COO
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.COO getCOO_AFABDetail_COO(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.COO result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.COO_AFABDetail_COO.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.COO.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of COO_AFABDetail_COO
	 * @param coo_afabdetail_coo
	 */
	public final void setCOO_AFABDetail_COO(mercedespoc.proxies.COO coo_afabdetail_coo)
	{
		setCOO_AFABDetail_COO(getContext(), coo_afabdetail_coo);
	}

	/**
	 * Set value of COO_AFABDetail_COO
	 * @param context
	 * @param coo_afabdetail_coo
	 */
	public final void setCOO_AFABDetail_COO(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.COO coo_afabdetail_coo)
	{
		if (coo_afabdetail_coo == null) {
			getMendixObject().setValue(context, MemberNames.COO_AFABDetail_COO.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.COO_AFABDetail_COO.toString(), coo_afabdetail_coo.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cOO_AFABDetailMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mercedespoc.proxies.COO_AFABDetail that = (mercedespoc.proxies.COO_AFABDetail) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
