// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public class Counters
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject countersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MercedesPOC.Counters";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CountAFAB("CountAFAB"),
		CountIDK("CountIDK"),
		CountCOO("CountCOO"),
		CountAVG_Min("CountAVG_Min"),
		CountAVG_Seconds("CountAVG_Seconds"),
		Counters_COO("MercedesPOC.Counters_COO"),
		Dashboard_Counters("MercedesPOC.Dashboard_Counters");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Counters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Counters(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject countersMendixObject)
	{
		if (countersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, countersMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.countersMendixObject = countersMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Counters.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mercedespoc.proxies.Counters initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mercedespoc.proxies.Counters.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mercedespoc.proxies.Counters initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mercedespoc.proxies.Counters(context, mendixObject);
	}

	public static mercedespoc.proxies.Counters load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mercedespoc.proxies.Counters.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CountAFAB
	 */
	public final java.lang.Integer getCountAFAB()
	{
		return getCountAFAB(getContext());
	}

	/**
	 * @param context
	 * @return value of CountAFAB
	 */
	public final java.lang.Integer getCountAFAB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountAFAB.toString());
	}

	/**
	 * Set value of CountAFAB
	 * @param countafab
	 */
	public final void setCountAFAB(java.lang.Integer countafab)
	{
		setCountAFAB(getContext(), countafab);
	}

	/**
	 * Set value of CountAFAB
	 * @param context
	 * @param countafab
	 */
	public final void setCountAFAB(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countafab)
	{
		getMendixObject().setValue(context, MemberNames.CountAFAB.toString(), countafab);
	}

	/**
	 * @return value of CountIDK
	 */
	public final java.lang.Integer getCountIDK()
	{
		return getCountIDK(getContext());
	}

	/**
	 * @param context
	 * @return value of CountIDK
	 */
	public final java.lang.Integer getCountIDK(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountIDK.toString());
	}

	/**
	 * Set value of CountIDK
	 * @param countidk
	 */
	public final void setCountIDK(java.lang.Integer countidk)
	{
		setCountIDK(getContext(), countidk);
	}

	/**
	 * Set value of CountIDK
	 * @param context
	 * @param countidk
	 */
	public final void setCountIDK(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countidk)
	{
		getMendixObject().setValue(context, MemberNames.CountIDK.toString(), countidk);
	}

	/**
	 * @return value of CountCOO
	 */
	public final java.lang.Integer getCountCOO()
	{
		return getCountCOO(getContext());
	}

	/**
	 * @param context
	 * @return value of CountCOO
	 */
	public final java.lang.Integer getCountCOO(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountCOO.toString());
	}

	/**
	 * Set value of CountCOO
	 * @param countcoo
	 */
	public final void setCountCOO(java.lang.Integer countcoo)
	{
		setCountCOO(getContext(), countcoo);
	}

	/**
	 * Set value of CountCOO
	 * @param context
	 * @param countcoo
	 */
	public final void setCountCOO(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countcoo)
	{
		getMendixObject().setValue(context, MemberNames.CountCOO.toString(), countcoo);
	}

	/**
	 * @return value of CountAVG_Min
	 */
	public final java.lang.Integer getCountAVG_Min()
	{
		return getCountAVG_Min(getContext());
	}

	/**
	 * @param context
	 * @return value of CountAVG_Min
	 */
	public final java.lang.Integer getCountAVG_Min(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountAVG_Min.toString());
	}

	/**
	 * Set value of CountAVG_Min
	 * @param countavg_min
	 */
	public final void setCountAVG_Min(java.lang.Integer countavg_min)
	{
		setCountAVG_Min(getContext(), countavg_min);
	}

	/**
	 * Set value of CountAVG_Min
	 * @param context
	 * @param countavg_min
	 */
	public final void setCountAVG_Min(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countavg_min)
	{
		getMendixObject().setValue(context, MemberNames.CountAVG_Min.toString(), countavg_min);
	}

	/**
	 * @return value of CountAVG_Seconds
	 */
	public final java.lang.Integer getCountAVG_Seconds()
	{
		return getCountAVG_Seconds(getContext());
	}

	/**
	 * @param context
	 * @return value of CountAVG_Seconds
	 */
	public final java.lang.Integer getCountAVG_Seconds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CountAVG_Seconds.toString());
	}

	/**
	 * Set value of CountAVG_Seconds
	 * @param countavg_seconds
	 */
	public final void setCountAVG_Seconds(java.lang.Integer countavg_seconds)
	{
		setCountAVG_Seconds(getContext(), countavg_seconds);
	}

	/**
	 * Set value of CountAVG_Seconds
	 * @param context
	 * @param countavg_seconds
	 */
	public final void setCountAVG_Seconds(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer countavg_seconds)
	{
		getMendixObject().setValue(context, MemberNames.CountAVG_Seconds.toString(), countavg_seconds);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Counters_COO
	 */
	public final mercedespoc.proxies.COO getCounters_COO() throws com.mendix.core.CoreException
	{
		return getCounters_COO(getContext());
	}

	/**
	 * @param context
	 * @return value of Counters_COO
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.COO getCounters_COO(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.COO result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Counters_COO.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.COO.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Counters_COO
	 * @param counters_coo
	 */
	public final void setCounters_COO(mercedespoc.proxies.COO counters_coo)
	{
		setCounters_COO(getContext(), counters_coo);
	}

	/**
	 * Set value of Counters_COO
	 * @param context
	 * @param counters_coo
	 */
	public final void setCounters_COO(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.COO counters_coo)
	{
		if (counters_coo == null) {
			getMendixObject().setValue(context, MemberNames.Counters_COO.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Counters_COO.toString(), counters_coo.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Dashboard_Counters
	 */
	public final mercedespoc.proxies.Dashboard getDashboard_Counters() throws com.mendix.core.CoreException
	{
		return getDashboard_Counters(getContext());
	}

	/**
	 * @param context
	 * @return value of Dashboard_Counters
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.Dashboard getDashboard_Counters(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.Dashboard result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Dashboard_Counters.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.Dashboard.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Dashboard_Counters
	 * @param dashboard_counters
	 */
	public final void setDashboard_Counters(mercedespoc.proxies.Dashboard dashboard_counters)
	{
		setDashboard_Counters(getContext(), dashboard_counters);
	}

	/**
	 * Set value of Dashboard_Counters
	 * @param context
	 * @param dashboard_counters
	 */
	public final void setDashboard_Counters(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.Dashboard dashboard_counters)
	{
		if (dashboard_counters == null) {
			getMendixObject().setValue(context, MemberNames.Dashboard_Counters.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Dashboard_Counters.toString(), dashboard_counters.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return countersMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mercedespoc.proxies.Counters that = (mercedespoc.proxies.Counters) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
