// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public class Dashboard
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dashboardMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MercedesPOC.Dashboard";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StartedOn("StartedOn"),
		EndedOn("EndedOn"),
		counting("counting"),
		Dashboard_COO("MercedesPOC.Dashboard_COO"),
		Dashboard_Counters("MercedesPOC.Dashboard_Counters");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Dashboard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Dashboard(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dashboardMendixObject)
	{
		if (dashboardMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dashboardMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dashboardMendixObject = dashboardMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Dashboard.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mercedespoc.proxies.Dashboard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mercedespoc.proxies.Dashboard.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mercedespoc.proxies.Dashboard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mercedespoc.proxies.Dashboard(context, mendixObject);
	}

	public static mercedespoc.proxies.Dashboard load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mercedespoc.proxies.Dashboard.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of StartedOn
	 */
	public final java.util.Date getStartedOn()
	{
		return getStartedOn(getContext());
	}

	/**
	 * @param context
	 * @return value of StartedOn
	 */
	public final java.util.Date getStartedOn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartedOn.toString());
	}

	/**
	 * Set value of StartedOn
	 * @param startedon
	 */
	public final void setStartedOn(java.util.Date startedon)
	{
		setStartedOn(getContext(), startedon);
	}

	/**
	 * Set value of StartedOn
	 * @param context
	 * @param startedon
	 */
	public final void setStartedOn(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startedon)
	{
		getMendixObject().setValue(context, MemberNames.StartedOn.toString(), startedon);
	}

	/**
	 * @return value of EndedOn
	 */
	public final java.util.Date getEndedOn()
	{
		return getEndedOn(getContext());
	}

	/**
	 * @param context
	 * @return value of EndedOn
	 */
	public final java.util.Date getEndedOn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndedOn.toString());
	}

	/**
	 * Set value of EndedOn
	 * @param endedon
	 */
	public final void setEndedOn(java.util.Date endedon)
	{
		setEndedOn(getContext(), endedon);
	}

	/**
	 * Set value of EndedOn
	 * @param context
	 * @param endedon
	 */
	public final void setEndedOn(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endedon)
	{
		getMendixObject().setValue(context, MemberNames.EndedOn.toString(), endedon);
	}

	/**
	 * @return value of counting
	 */
	public final java.lang.Integer getcounting()
	{
		return getcounting(getContext());
	}

	/**
	 * @param context
	 * @return value of counting
	 */
	public final java.lang.Integer getcounting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.counting.toString());
	}

	/**
	 * Set value of counting
	 * @param counting
	 */
	public final void setcounting(java.lang.Integer counting)
	{
		setcounting(getContext(), counting);
	}

	/**
	 * Set value of counting
	 * @param context
	 * @param counting
	 */
	public final void setcounting(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer counting)
	{
		getMendixObject().setValue(context, MemberNames.counting.toString(), counting);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Dashboard_COO
	 */
	public final mercedespoc.proxies.COO getDashboard_COO() throws com.mendix.core.CoreException
	{
		return getDashboard_COO(getContext());
	}

	/**
	 * @param context
	 * @return value of Dashboard_COO
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.COO getDashboard_COO(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.COO result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Dashboard_COO.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.COO.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Dashboard_COO
	 * @param dashboard_coo
	 */
	public final void setDashboard_COO(mercedespoc.proxies.COO dashboard_coo)
	{
		setDashboard_COO(getContext(), dashboard_coo);
	}

	/**
	 * Set value of Dashboard_COO
	 * @param context
	 * @param dashboard_coo
	 */
	public final void setDashboard_COO(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.COO dashboard_coo)
	{
		if (dashboard_coo == null) {
			getMendixObject().setValue(context, MemberNames.Dashboard_COO.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Dashboard_COO.toString(), dashboard_coo.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Dashboard_Counters
	 */
	public final mercedespoc.proxies.Counters getDashboard_Counters() throws com.mendix.core.CoreException
	{
		return getDashboard_Counters(getContext());
	}

	/**
	 * @param context
	 * @return value of Dashboard_Counters
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.Counters getDashboard_Counters(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.Counters result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Dashboard_Counters.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.Counters.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Dashboard_Counters
	 * @param dashboard_counters
	 */
	public final void setDashboard_Counters(mercedespoc.proxies.Counters dashboard_counters)
	{
		setDashboard_Counters(getContext(), dashboard_counters);
	}

	/**
	 * Set value of Dashboard_Counters
	 * @param context
	 * @param dashboard_counters
	 */
	public final void setDashboard_Counters(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.Counters dashboard_counters)
	{
		if (dashboard_counters == null) {
			getMendixObject().setValue(context, MemberNames.Dashboard_Counters.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Dashboard_Counters.toString(), dashboard_counters.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dashboardMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mercedespoc.proxies.Dashboard that = (mercedespoc.proxies.Dashboard) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
