// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public class DatafieldsTable
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject datafieldsTableMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MercedesPOC.DatafieldsTable";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Entryvalue("Entryvalue"),
		DatafieldsTable_AFABFields("MercedesPOC.DatafieldsTable_AFABFields"),
		DatafieldsTable_Geography("MercedesPOC.DatafieldsTable_Geography");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DatafieldsTable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DatafieldsTable(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject datafieldsTableMendixObject)
	{
		if (datafieldsTableMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, datafieldsTableMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.datafieldsTableMendixObject = datafieldsTableMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DatafieldsTable.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mercedespoc.proxies.DatafieldsTable initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mercedespoc.proxies.DatafieldsTable.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mercedespoc.proxies.DatafieldsTable initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mercedespoc.proxies.DatafieldsTable(context, mendixObject);
	}

	public static mercedespoc.proxies.DatafieldsTable load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mercedespoc.proxies.DatafieldsTable.initialize(context, mendixObject);
	}

	public static java.util.List<mercedespoc.proxies.DatafieldsTable> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mercedespoc.proxies.DatafieldsTable.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Entryvalue
	 */
	public final java.lang.String getEntryvalue()
	{
		return getEntryvalue(getContext());
	}

	/**
	 * @param context
	 * @return value of Entryvalue
	 */
	public final java.lang.String getEntryvalue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Entryvalue.toString());
	}

	/**
	 * Set value of Entryvalue
	 * @param entryvalue
	 */
	public final void setEntryvalue(java.lang.String entryvalue)
	{
		setEntryvalue(getContext(), entryvalue);
	}

	/**
	 * Set value of Entryvalue
	 * @param context
	 * @param entryvalue
	 */
	public final void setEntryvalue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String entryvalue)
	{
		getMendixObject().setValue(context, MemberNames.Entryvalue.toString(), entryvalue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DatafieldsTable_AFABFields
	 */
	public final mercedespoc.proxies.AFABFields getDatafieldsTable_AFABFields() throws com.mendix.core.CoreException
	{
		return getDatafieldsTable_AFABFields(getContext());
	}

	/**
	 * @param context
	 * @return value of DatafieldsTable_AFABFields
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.AFABFields getDatafieldsTable_AFABFields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.AFABFields result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DatafieldsTable_AFABFields.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.AFABFields.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DatafieldsTable_AFABFields
	 * @param datafieldstable_afabfields
	 */
	public final void setDatafieldsTable_AFABFields(mercedespoc.proxies.AFABFields datafieldstable_afabfields)
	{
		setDatafieldsTable_AFABFields(getContext(), datafieldstable_afabfields);
	}

	/**
	 * Set value of DatafieldsTable_AFABFields
	 * @param context
	 * @param datafieldstable_afabfields
	 */
	public final void setDatafieldsTable_AFABFields(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.AFABFields datafieldstable_afabfields)
	{
		if (datafieldstable_afabfields == null) {
			getMendixObject().setValue(context, MemberNames.DatafieldsTable_AFABFields.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DatafieldsTable_AFABFields.toString(), datafieldstable_afabfields.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DatafieldsTable_Geography
	 */
	public final mercedespoc.proxies.Geography getDatafieldsTable_Geography() throws com.mendix.core.CoreException
	{
		return getDatafieldsTable_Geography(getContext());
	}

	/**
	 * @param context
	 * @return value of DatafieldsTable_Geography
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.Geography getDatafieldsTable_Geography(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.Geography result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DatafieldsTable_Geography.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.Geography.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DatafieldsTable_Geography
	 * @param datafieldstable_geography
	 */
	public final void setDatafieldsTable_Geography(mercedespoc.proxies.Geography datafieldstable_geography)
	{
		setDatafieldsTable_Geography(getContext(), datafieldstable_geography);
	}

	/**
	 * Set value of DatafieldsTable_Geography
	 * @param context
	 * @param datafieldstable_geography
	 */
	public final void setDatafieldsTable_Geography(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.Geography datafieldstable_geography)
	{
		if (datafieldstable_geography == null) {
			getMendixObject().setValue(context, MemberNames.DatafieldsTable_Geography.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DatafieldsTable_Geography.toString(), datafieldstable_geography.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return datafieldsTableMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mercedespoc.proxies.DatafieldsTable that = (mercedespoc.proxies.DatafieldsTable) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
