// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public enum ENUM_ProcessStatus
{
	_New(new java.lang.String[][] { new java.lang.String[] { "en_US", "New" } }),
	Pending_AFAB_Validation(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pending AFAB Validation" } }),
	Pending_IHK_Draft_Validation(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pending IHK Draft Validation" } }),
	Submited(new java.lang.String[][] { new java.lang.String[] { "en_US", "Submitted" } }),
	Fetching_From_AFAB(new java.lang.String[][] { new java.lang.String[] { "en_US", "Fetching From AFAB" } }),
	Submitting_as_Draft(new java.lang.String[][] { new java.lang.String[] { "en_US", "Submitting as Draft" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_ProcessStatus(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
