// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public enum ENUM_AFABFields
{
	Chassis_Number(new java.lang.String[][] { new java.lang.String[] { "en_US", "Chassis Number" } }),
	Weight(new java.lang.String[][] { new java.lang.String[] { "en_US", "Weight" } }),
	Engine_Nr(new java.lang.String[][] { new java.lang.String[] { "en_US", "Engine Number" } }),
	Model_Year(new java.lang.String[][] { new java.lang.String[] { "en_US", "Model Year" } }),
	Production_Finish(new java.lang.String[][] { new java.lang.String[] { "en_US", "Production Finish" } }),
	Ex_Factory_Date(new java.lang.String[][] { new java.lang.String[] { "en_US", "Ex Factory Date" } }),
	Color_Of_Chassis(new java.lang.String[][] { new java.lang.String[] { "en_US", "Color Of Chassis" } }),
	Address(new java.lang.String[][] { new java.lang.String[] { "en_US", "Address" } }),
	CustomerAdress(new java.lang.String[][] { new java.lang.String[] { "en_US", "Customer Address" } }),
	Country(new java.lang.String[][] { new java.lang.String[] { "en_US", "Customer Country" } }),
	MeansOfTransport(new java.lang.String[][] { new java.lang.String[] { "en_US", "Means Of Transport" } }),
	Quantity(new java.lang.String[][] { new java.lang.String[] { "en_US", "Quantity" } }),
	Description(new java.lang.String[][] { new java.lang.String[] { "en_US", "Description" } }),
	ComissionNumber(new java.lang.String[][] { new java.lang.String[] { "en_US", "Comission Number" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_AFABFields(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
