// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public class GeographyFilter
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject geographyFilterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MercedesPOC.GeographyFilter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GeographyCode("GeographyCode"),
		StatusFilter("StatusFilter"),
		GeographyFilter_Geography("MercedesPOC.GeographyFilter_Geography");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GeographyFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GeographyFilter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject geographyFilterMendixObject)
	{
		if (geographyFilterMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, geographyFilterMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.geographyFilterMendixObject = geographyFilterMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GeographyFilter.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mercedespoc.proxies.GeographyFilter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mercedespoc.proxies.GeographyFilter.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mercedespoc.proxies.GeographyFilter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mercedespoc.proxies.GeographyFilter(context, mendixObject);
	}

	public static mercedespoc.proxies.GeographyFilter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mercedespoc.proxies.GeographyFilter.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of GeographyCode
	 */
	public final java.lang.String getGeographyCode()
	{
		return getGeographyCode(getContext());
	}

	/**
	 * @param context
	 * @return value of GeographyCode
	 */
	public final java.lang.String getGeographyCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GeographyCode.toString());
	}

	/**
	 * Set value of GeographyCode
	 * @param geographycode
	 */
	public final void setGeographyCode(java.lang.String geographycode)
	{
		setGeographyCode(getContext(), geographycode);
	}

	/**
	 * Set value of GeographyCode
	 * @param context
	 * @param geographycode
	 */
	public final void setGeographyCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String geographycode)
	{
		getMendixObject().setValue(context, MemberNames.GeographyCode.toString(), geographycode);
	}

	/**
	 * Set value of StatusFilter
	 * @param statusfilter
	 */
	public final mercedespoc.proxies.ENUM_ProcessStatus getStatusFilter()
	{
		return getStatusFilter(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusFilter
	 */
	public final mercedespoc.proxies.ENUM_ProcessStatus getStatusFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.StatusFilter.toString());
		if (obj == null) {
			return null;
		}
		return mercedespoc.proxies.ENUM_ProcessStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of StatusFilter
	 * @param statusfilter
	 */
	public final void setStatusFilter(mercedespoc.proxies.ENUM_ProcessStatus statusfilter)
	{
		setStatusFilter(getContext(), statusfilter);
	}

	/**
	 * Set value of StatusFilter
	 * @param context
	 * @param statusfilter
	 */
	public final void setStatusFilter(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.ENUM_ProcessStatus statusfilter)
	{
		if (statusfilter != null) {
			getMendixObject().setValue(context, MemberNames.StatusFilter.toString(), statusfilter.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.StatusFilter.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GeographyFilter_Geography
	 */
	public final mercedespoc.proxies.Geography getGeographyFilter_Geography() throws com.mendix.core.CoreException
	{
		return getGeographyFilter_Geography(getContext());
	}

	/**
	 * @param context
	 * @return value of GeographyFilter_Geography
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.Geography getGeographyFilter_Geography(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.Geography result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GeographyFilter_Geography.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.Geography.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GeographyFilter_Geography
	 * @param geographyfilter_geography
	 */
	public final void setGeographyFilter_Geography(mercedespoc.proxies.Geography geographyfilter_geography)
	{
		setGeographyFilter_Geography(getContext(), geographyfilter_geography);
	}

	/**
	 * Set value of GeographyFilter_Geography
	 * @param context
	 * @param geographyfilter_geography
	 */
	public final void setGeographyFilter_Geography(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.Geography geographyfilter_geography)
	{
		if (geographyfilter_geography == null) {
			getMendixObject().setValue(context, MemberNames.GeographyFilter_Geography.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GeographyFilter_Geography.toString(), geographyfilter_geography.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return geographyFilterMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mercedespoc.proxies.GeographyFilter that = (mercedespoc.proxies.GeographyFilter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
