// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public class Geography
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject geographyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MercedesPOC.Geography";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GeographyName("GeographyName"),
		GeographyCode("GeographyCode"),
		Geography_AFABFields("MercedesPOC.Geography_AFABFields");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Geography(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Geography(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject geographyMendixObject)
	{
		if (geographyMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, geographyMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.geographyMendixObject = geographyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Geography.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mercedespoc.proxies.Geography initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mercedespoc.proxies.Geography.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mercedespoc.proxies.Geography initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mercedespoc.proxies.Geography(context, mendixObject);
	}

	public static mercedespoc.proxies.Geography load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mercedespoc.proxies.Geography.initialize(context, mendixObject);
	}

	public static java.util.List<mercedespoc.proxies.Geography> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mercedespoc.proxies.Geography.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of GeographyName
	 */
	public final java.lang.String getGeographyName()
	{
		return getGeographyName(getContext());
	}

	/**
	 * @param context
	 * @return value of GeographyName
	 */
	public final java.lang.String getGeographyName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GeographyName.toString());
	}

	/**
	 * Set value of GeographyName
	 * @param geographyname
	 */
	public final void setGeographyName(java.lang.String geographyname)
	{
		setGeographyName(getContext(), geographyname);
	}

	/**
	 * Set value of GeographyName
	 * @param context
	 * @param geographyname
	 */
	public final void setGeographyName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String geographyname)
	{
		getMendixObject().setValue(context, MemberNames.GeographyName.toString(), geographyname);
	}

	/**
	 * @return value of GeographyCode
	 */
	public final java.lang.String getGeographyCode()
	{
		return getGeographyCode(getContext());
	}

	/**
	 * @param context
	 * @return value of GeographyCode
	 */
	public final java.lang.String getGeographyCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GeographyCode.toString());
	}

	/**
	 * Set value of GeographyCode
	 * @param geographycode
	 */
	public final void setGeographyCode(java.lang.String geographycode)
	{
		setGeographyCode(getContext(), geographycode);
	}

	/**
	 * Set value of GeographyCode
	 * @param context
	 * @param geographycode
	 */
	public final void setGeographyCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String geographycode)
	{
		getMendixObject().setValue(context, MemberNames.GeographyCode.toString(), geographycode);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Geography_AFABFields
	 */
	public final java.util.List<mercedespoc.proxies.AFABFields> getGeography_AFABFields() throws com.mendix.core.CoreException
	{
		return getGeography_AFABFields(getContext());
	}

	/**
	 * @param context
	 * @return value of Geography_AFABFields
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mercedespoc.proxies.AFABFields> getGeography_AFABFields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<mercedespoc.proxies.AFABFields> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Geography_AFABFields.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(mercedespoc.proxies.AFABFields.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Geography_AFABFields
	 * @param geography_afabfields
	 */
	public final void setGeography_AFABFields(java.util.List<mercedespoc.proxies.AFABFields> geography_afabfields)
	{
		setGeography_AFABFields(getContext(), geography_afabfields);
	}

	/**
	 * Set value of Geography_AFABFields
	 * @param context
	 * @param geography_afabfields
	 */
	public final void setGeography_AFABFields(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<mercedespoc.proxies.AFABFields> geography_afabfields)
	{
		var identifiers = geography_afabfields
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Geography_AFABFields.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return geographyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mercedespoc.proxies.Geography that = (mercedespoc.proxies.Geography) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
