// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mercedespoc.proxies;

public class helper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject helperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MercedesPOC.helper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		helper_Geography("MercedesPOC.helper_Geography"),
		helper_AFABFields("MercedesPOC.helper_AFABFields"),
		helper_DatafieldsTable("MercedesPOC.helper_DatafieldsTable");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public helper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected helper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject helperMendixObject)
	{
		if (helperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, helperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.helperMendixObject = helperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'helper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mercedespoc.proxies.helper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mercedespoc.proxies.helper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mercedespoc.proxies.helper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mercedespoc.proxies.helper(context, mendixObject);
	}

	public static mercedespoc.proxies.helper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mercedespoc.proxies.helper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of helper_Geography
	 */
	public final java.util.List<mercedespoc.proxies.Geography> gethelper_Geography() throws com.mendix.core.CoreException
	{
		return gethelper_Geography(getContext());
	}

	/**
	 * @param context
	 * @return value of helper_Geography
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mercedespoc.proxies.Geography> gethelper_Geography(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<mercedespoc.proxies.Geography> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.helper_Geography.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(mercedespoc.proxies.Geography.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of helper_Geography
	 * @param helper_geography
	 */
	public final void sethelper_Geography(java.util.List<mercedespoc.proxies.Geography> helper_geography)
	{
		sethelper_Geography(getContext(), helper_geography);
	}

	/**
	 * Set value of helper_Geography
	 * @param context
	 * @param helper_geography
	 */
	public final void sethelper_Geography(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<mercedespoc.proxies.Geography> helper_geography)
	{
		var identifiers = helper_geography
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.helper_Geography.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of helper_AFABFields
	 */
	public final java.util.List<mercedespoc.proxies.AFABFields> gethelper_AFABFields() throws com.mendix.core.CoreException
	{
		return gethelper_AFABFields(getContext());
	}

	/**
	 * @param context
	 * @return value of helper_AFABFields
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mercedespoc.proxies.AFABFields> gethelper_AFABFields(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<mercedespoc.proxies.AFABFields> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.helper_AFABFields.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(mercedespoc.proxies.AFABFields.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of helper_AFABFields
	 * @param helper_afabfields
	 */
	public final void sethelper_AFABFields(java.util.List<mercedespoc.proxies.AFABFields> helper_afabfields)
	{
		sethelper_AFABFields(getContext(), helper_afabfields);
	}

	/**
	 * Set value of helper_AFABFields
	 * @param context
	 * @param helper_afabfields
	 */
	public final void sethelper_AFABFields(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<mercedespoc.proxies.AFABFields> helper_afabfields)
	{
		var identifiers = helper_afabfields
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.helper_AFABFields.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of helper_DatafieldsTable
	 */
	public final mercedespoc.proxies.DatafieldsTable gethelper_DatafieldsTable() throws com.mendix.core.CoreException
	{
		return gethelper_DatafieldsTable(getContext());
	}

	/**
	 * @param context
	 * @return value of helper_DatafieldsTable
	 * @throws com.mendix.core.CoreException
	 */
	public final mercedespoc.proxies.DatafieldsTable gethelper_DatafieldsTable(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mercedespoc.proxies.DatafieldsTable result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.helper_DatafieldsTable.toString());
		if (identifier != null) {
			result = mercedespoc.proxies.DatafieldsTable.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of helper_DatafieldsTable
	 * @param helper_datafieldstable
	 */
	public final void sethelper_DatafieldsTable(mercedespoc.proxies.DatafieldsTable helper_datafieldstable)
	{
		sethelper_DatafieldsTable(getContext(), helper_datafieldstable);
	}

	/**
	 * Set value of helper_DatafieldsTable
	 * @param context
	 * @param helper_datafieldstable
	 */
	public final void sethelper_DatafieldsTable(com.mendix.systemwideinterfaces.core.IContext context, mercedespoc.proxies.DatafieldsTable helper_datafieldstable)
	{
		if (helper_datafieldstable == null) {
			getMendixObject().setValue(context, MemberNames.helper_DatafieldsTable.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.helper_DatafieldsTable.toString(), helper_datafieldstable.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return helperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mercedespoc.proxies.helper that = (mercedespoc.proxies.helper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
