// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package importmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the ImportModule module
	public static void aCT_ImportCOOs(IContext context, importmodule.proxies.ImportCOOHelper _importCOOHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ImportCOOHelper", _importCOOHelper == null ? null : _importCOOHelper.getMendixObject());
		Core.microflowCall("ImportModule.ACT_ImportCOOs").withParams(params).execute(context);
	}
	public static java.lang.String parseOrderNumber(IContext context, java.lang.String _inputString)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("InputString", _inputString);
		return (java.lang.String) Core.microflowCall("ImportModule.ParseOrderNumber").withParams(params).execute(context);
	}
}
